# Generated by Django 2.2.6 on 2019-10-23 18:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=10, verbose_name='Функции')),
            ],
            options={
                'verbose_name': 'Функция',
                'verbose_name_plural': 'Функции',
                'ordering': ['formula'],
            },
        ),
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='image', verbose_name='График')),
                ('interval', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Интервал t, дней')),
                ('dt', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Шаг t, часы')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Дата обработки')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Functions', verbose_name='Функция')),
            ],
            options={
                'verbose_name': 'График',
                'verbose_name_plural': 'Графики',
                'ordering': ['formula'],
            },
        ),
    ]
